name: cnnSearch
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=1.5.0
  - torchvision>=0.6.0
  - pytorch-cuda=11.8
  - onnx
  - pip
  - pip:
    - cython
    - submitit
    - scipy
    - onnxruntime
    - model-compression-toolkit
    - safe_gpu
